language: ruby
rvm:
  - 2.2.3
env:
  global:
    - secure: "gpOydc0w4uUE1r2y6LDXbDJqeSNAHiK5iXvmJ/0CpnLKipCNVZ9B4eQDFq9es8BriFnh8zcdM/oNzVF31qXuS5XfnPQBwQ/g/kgcYKxDmlR7NS/Gd6eSzFkxbMzRmzaQpXZqTawg3bUpyyN/uheN3uWpO//iAP8LESZr4BzGtog="
    - FAUNA_DOMAIN=rest.faunadb.com
    - FAUNA_SCHEME=https
    - FAUNA_PORT=443
