language: ruby
env:
  global:
    - FAUNA_ROOT_KEY=secret
    - FAUNA_DOMAIN=localhost
    - FAUNA_SCHEME=http
    - FAUNA_PORT=8443
rvm:
  - 2.2.3
jdk:
  - oraclejdk8
before_install:
  - openssl aes-256-cbc -K $encrypted_7c62f1a9621e_key -iv $encrypted_7c62f1a9621e_iv -in core.tgz.enc -out core.tgz -d
  - tar zxf core.tgz
  - sh install-core.sh
